### ISSUE TITLE
Data generation for testing purposes

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#1]
This issue requires two things:

- [x] Adapt current scripts written by Rob Clay to read in indresp files from Understanding Society and impute some things (need lots of last observation carried forward (locf) imputation for things like ethnicity) 
- [x] Remove any other files that were part of Rob's PhD work and not needed for this (especially scripts in persistent data)

We need a file or collection of files as a starting point that we can use to run some exploratory regressions and other investigatory work.

**Comment by ld-archer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Rob's data generation script to add more columns to the outputs](https://trello.com/c/S16uwhiE/18-update-robs-data-generation-script-to-add-more-columns-to-the-outputs)

**Comment by ld-archer** [comment]
I've changed the US_format_raw.py script to merge the hhresp datafile to indresp based on hidp, so we can include household variables alongside individual. I'm now going to add the variables from Niks document ('Calculations of Understanding Society variables to correspond to SIPHER 7 domains') that relate to housing quality:

Quality 				of housing | Your 				home is in a reasonable 				state of repair, 				has reasonable 				facilities (cooking/washing) and 				provides reasonable 				warmth 				… | 1) 				Yes to all of these / 2) yes to some of these / 3) none of these | 1. 				Sum up housing 				= i_cduse5 				+ i_cduse6 				+ 				i_cduse7 				+ 				i_cduse8 				+ i_cduse9 				+ i_hheat 				(0=No, 				1=Yes); 				2. 				Make housing=6 				as the “Yes to all of these”, housing=0 				as the “none of these”, and others as the “yes to some of 				these”.
-- | -- | -- | --

N.B. the only variable here that does not run for the length of both BHPS and the UKHLS is `i_hheat`. This is a UKHLS variable that has a similar variable in BHPS (`hsprbk` - Accom: lack of adequate heating), except that the BHPS var is the opposite - UKHLS asks if home is warm enough, BHPS asks if home has lack of adequate heating. Because of this, I'll need to flip the BHPS var.

**Comment by ld-archer** [comment]
Housing quality variables are now added to the raw_US/ formatted files. Some important things to note:
- `cduse5` & `cduse7` are both missing for wave 6 of the BHPS (1995)
- The heating variable is derived from both `hheat` in ukhls and `hsprbk` in BHPS as mentioned above
- `hheat` is missing in the ukhls in waves 3, 5, & 7 (2010, 2012, 2014)

Final thing to fix is the `US_missing_main.py` script as it is producing blank csv's since updating `US_format_raw.py`

**Comment by RobertClay** [comment]
If you have a couple of missing waves for `cduse` I suggest this update to the function in US_Utils


def subset_data(data, required_columns, column_names, substitute = True):
    """ Take desired columns from US data and rename them.

    Parameters
    ----------
    data : pd.DataFrame
        Loaded in data from csv.
    required_columns : list
        Which subset of columns is being taken.
    column_names : list
        New names for dataframe columns. Makes it clearer for use in microsim.
    substitute : bool
        If specified variables arent present in a specific wave of US data then substitute
        it with an empty column for that wave. For example depression (hcond17) is not available in wave 2 of UKHLS but
        is available in all other waves. Setting substitute = True replaces the variable in wave 2 with an empty column.
        Is entirely empty data but preserves consistent data across all waves for later imputation. Otherwise will
        raise a key error.

    Returns
    -------
    data : pd.DataFrame
        Subset of initial data with desired columns.
    """
    # Take subset of data for required columns and rename them.
    if substitute:
        for item in required_columns:
            if item not in data.columns:
                data[item] = -9
                print(f"Warning! {item} not found in wave {alphabet.find(item[0])+1}. Substituting a dummy column. "
                      + "Set substitute = False in the subset_data function to suppress this behaviour.")
    data = data[required_columns]
    data.columns = column_names
    return data

**Comment by RobertClay** [comment]
will leave entire columns empty but consistent data which is nice
