### ISSUE TITLE
scotland subsetting. 

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#118]
- [x] scotland transitions. add new scotland_coefficients.txt file for scotland transition on smaller dataset without region variable.
- [x] subsetting data. just use function US_subsetting to get the scots and output to scotland_US dataset. 
- [ ] needs some testing.. make baseline should work. 
- [x] Any additional makecommands. can just run US_subsetting directly in console but worth a make command for just scots for future use?

**Comment by RobertClay** [comment]
subsetting functions are done. maybe needs adding to makefiles as a seperate scot_data command..?

**Comment by ld-archer** [comment]
I'll do the transitions stuff in a separate branch and PR to development.

**Comment by RobertClay** [comment]
maps for scotland.

**Comment by ld-archer** [comment]
Have merged this stuff into a branch called `scotland_mode`. I'm going to open a new issue for Scotland mode stuff, so closing this one.
