### ISSUE TITLE
Investigate removing requirements.txt entirely

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#130]
From #126, only vivarium left in requirements.txt as is makefile target. Look at removing entirely. Would allow removal of INSTALL_REQUIRES entirely from setup.py.

**Comment by paddy-r** [comment]
Shuffled Makefile, setup.py, environment.yml around; removed requirements.txt; corrections to readme and environment.yml based on Rob's testing -> installation now as simple as possible (although vivarium still specified explicitly in setup.py, and short of implementing pyproject.toml and removing setup.py entirely).

**Comment by NGRhodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make vivarium initialisation saner](https://trello.com/c/L9NhlfyM/3-make-vivarium-initialisation-saner)
