### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#14]
Create docker image with working python environment. 

More up to date numpy/pandas/vivarium for more functionality. 
remove vivarium population spenser utils as package is deprecated.

need discussion on how to do this and what else to include.

**Comment by ld-archer** [comment]
`minos` image created and available on the dockerhub [here](https://hub.docker.com/r/ldarcher/minos).

Planning to move to a master and develop branch so will have the docker build from master and push changes from develop when we're happy with them.
