### ISSUE TITLE
Add to missingness pipeline: Hotdecking within wave missing, Interpolating whole wave missing

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#15]
Need to handle missing information:
- Hotdecking when missing for some records within a wave
- Interpolation when the whole wave is missing a variable

**Comment by RobertClay** [comment]
- [ ] get us files post locf ready for imputation techniques.
- [ ] hot deck imputation files. knn attempt first.
- [ ] look up mathods for imputing entire empty columns.
- [ ] try and implement any

**Comment by RobertClay** [comment]
MICE working in notebooks but need massively beefing up for Sheff folks. See MICE vignettes for similar flowstyle. Also discussion on longitudinal imputation and why its difficult.

**Comment by RobertClay** [comment]
closing as old/vague. better issues exist
