### ISSUE TITLE
Fake Council tax data

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#16]
In lieu of real council tax being special access need to create fake individual council tax data. 

- [x] Get individual council tax bands
- [x] Get council tax bands by area (min, max, mean)
- [x] Draw randomly from this band to get a fake council tax (truncated normal/ uniform?)
- [ ] Any other stratification to improve fit? council type urban/rural? london poll tax boosting? inflation? household students / other combinations?

**Comment by RobertClay** [comment]
data only for great britain. Northern Ireland has different system (yay). Uses a percentage of house value for what to charge. https://www.which.co.uk/money/tax/council-tax/council-tax-bands-apxvz5j37h67#headline_6

Need to calculate this for NI seperately.

**Comment by RobertClay** [comment]
also Im not doing NI for now it looks awful.

**Comment by ld-archer** [comment]
Great stuff, I've merged the changes from here into 17_household-income so I'll close them both with a pull request soon
