### ISSUE TITLE
Calculate household income

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#17]
Summary of how to calculate household income, after housing costs, adjusted for household size

Link: https://www.understandingsociety.ac.uk/documentation/mainstage/user-guides/main-survey-user-guide/household-income-variables 

Start with net household monthly income
w_fihhmnnet1_dv+

Remove housing costs
Rented: w_rentgrs_dv
Mortgage: w_xpmg_dv
Remove council tax: w_ficountax_dv

Adjust for size of household
Multiply by: w_ ieqmoecd_dv

Adjust for inflation for comparability
See ‘price indices’ in the above link

Need to use Rob's fake council tax values in place of the real variable as the var is only available in the special licence version of US. See #16 for more info

**Comment by ld-archer** [comment]
## Summary Statistics
---

These figures are after adjusting for inflation.
```
mean       1640.240461
std        2711.355789
min      -90270.919889
25%         935.831643
50%        1393.337246
75%        2007.574556
max      800645.207524
```
Histogram of full data:
![image](https://user-images.githubusercontent.com/44437206/156734105-d6282699-f81c-4332-b095-e2b44061af12.png)

All this histogram tells us is that the right tail is very long but makes up a tiny number of cases. The vast majority of records fall between `-5000 < x < 25000` (455,063/455,354).

Another histogram within this bracket:
![image](https://user-images.githubusercontent.com/44437206/156734849-67311c2f-7ac0-4a50-a032-d797b0ea661a.png)

Final hist showing -5000 -> 5000:
![image](https://user-images.githubusercontent.com/44437206/156734933-650abadd-9d56-4dfc-bd7d-5d4a92ea2d4b.png)

**Missingness**:

37,913 / 455,354 missing records, or 8.3%.

By age:
![image](https://user-images.githubusercontent.com/44437206/156775361-ad27712f-d9ed-4665-935f-69a846eba638.png)

**Comment by RobertClay** [comment]
noice. be intereseted to see what people on the extreme ends look like. I'd expect anyone earning negatives to not have to work or genuinely be in trouble. Upper end probably cool too but not relevant ot msim

**Comment by RobertClay** [comment]
could also be my fake council tax pushing them into negatives.

**Comment by RobertClay** [comment]
missingness makes sense too if only change in variables recorded (-8 otherwise). Or just old people less likely to earn money.

**Comment by ld-archer** [comment]
### Negative Household Income
---
**Age**
![image](https://user-images.githubusercontent.com/44437206/157007327-56e440f5-5964-44c6-b13f-cd7bbf833a62.png)
**Education State**
![image](https://user-images.githubusercontent.com/44437206/157010081-c125f3a7-9b35-465b-b4b9-d8c7dd3ab600.png)
**Labour State**
![image](https://user-images.githubusercontent.com/44437206/157009370-042669aa-8792-40be-9e4e-66d501b94741.png)
**NSSEC**
![image](https://user-images.githubusercontent.com/44437206/157009626-a9e7bf47-bf3e-479b-af63-f4a9351acde6.png)
**Region**
![image](https://user-images.githubusercontent.com/44437206/157009775-59a4f577-5180-41ee-b26b-032db1689675.png)
**Ethnicity**
![image](https://user-images.githubusercontent.com/44437206/157009932-ddd9c368-b906-40cf-bcd7-63f29357920f.png)

**Comment by ld-archer** [comment]
Think the above plots are reasonable, don't seem to show anything abnormal. The negative wage group are more likely to be:
- not in employment (i.e. student, unemployed) 
- Young adult (probably overlap with student as age spike around 20)
- self-employed
- small business owner
- Educated to A-level
- London resident
