### ISSUE TITLE
reducing number of calls to rpy2

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#174]
Some way to reduce the number of calls to rpy2. 

Initial thought is some kind of object that holds the classes preloaded for each model run. 
Would reduce number of calls to about 1% (150k -> 1500)

Worth consulting with John Hodrien to see if he can think of anything better.
Maybe worth looking into pickle to store one object with these preloaded packages in? Will rpy2 cooperate with pickle? Unlikely.. https://rpy.sourceforge.io/rpy2/doc-dev/html/robjects_serialization.html

**Comment by ld-archer** [comment]
Don't know about pickle's but I think we would get the same benefit loading them into any object. I reckon the easiest way to tackle this is to save them into the simulation object during pre-setup with the `simulation._data.write()` function, then pass them to the on_time_step methods (or I think they would already be accessible in `self.`?).

**Comment by RobertClay** [comment]
Yeah agreed. Pickle is ambitious but may only need one for the whole set of runs. Simpler to load into builder

**Comment by RobertClay** [comment]
loading rpy2 packages as objects in vivarium builder seems to fix the issue. may still be able to limit number of conversions between rpy2 and pandas but very difficult to do..

**Comment by RobertClay** [comment]
![minos_uml](https://user-images.githubusercontent.com/45287106/223140458-a01f89ac-4412-4cb3-a9ce-aba2f065bfd0.png)
