### ISSUE TITLE
Investigate the final Scottish sample 

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#180]
The final Scottish only sample from Understanding Society for running in Scotland mode is roughly half the original sample (~1500/3000). This is a 50% loss rate, which is most likely from the complete case removals of specific variables needed for the model to run. 

We should investigate who is being removed during the data generation pipeline and is eventually in the starting population. 

Comparison plots:
- [ ] Demographics
    - Age
    - Sex
    - Education
    - Ethnicity (limited in Scottish sample)
    - More?
- [ ] Household Income
- [ ] SF_12
- [ ] Pathways
    - Housing quality
    - Neighbourhood safety
    - Nutrition quality
    - Tobacco use
    - Loneliness

**Comment by RobertClay** [comment]
think this is superceded by scottish synthpop?
