### ISSUE TITLE
investigate interventions

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#191]
Originally planned to open this intervention to look into problems with the energy downlift intervention, however without changing anything in the development branch this intervention now looks as we would expect, and the all child uplift has gone to pot. I figure that any work investigating and plotting outputs from interventions will be useful in many situations going forward.

I'm going to add lots of plots and analysis to minos/validation/interventions.Rmd to try and learn a bit more about them.

Ideas:
- [ ] Visualise changes in pathway variables to make sure hh_income changes are perpetuating through the model
- [ ] Calculate the number of people that have an SF12 increase due to the intervention (same with decrease)
    - Average increase/decrease for each group? 
- [ ] Starting SF12 values for each targeted group. i.e. Does the living wage boosted group actually have starting SF12 below baseline as we suspect?
- [ ] MORE

Here is the starting state of the intervention output plots:
![all_child_uplift_SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203490-222a6986-e124-4bc7-9d56-86559eca4110.png)
![poverty_line_child_uplift_SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203582-ca15881c-2d8c-4eb4-aaaa-edea72e38a96.png)
![living_wage_treated_SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203608-a80d1c09-0154-4c2e-ae72-3fbb2d736c63.png)
![energy_downlift_SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203640-98e614d9-7ac1-4065-9a01-ecedf077be46.png)
![treated_SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203685-ab780cce-1651-4b47-b8c0-1ce678a36f6c.png)
![SF_12_aggs_by_year-1](https://user-images.githubusercontent.com/44437206/222203706-b65ddd80-2a96-4afe-ac04-5b255bab36f0.png)

**Comment by ld-archer** [comment]
## Deep Dive on Energy Downlift

Picked the energy downlift intervention because it has the largest hh_income change, which translates into the largest pathways changes.

### Household Income
Household income shows a clear intervention effect, where hh_income is substantially reduced in the energy downlift.
![ED_hh_income](https://user-images.githubusercontent.com/44437206/222235550-45f4d109-493b-43d1-9426-5826d27c1dcd.png)
### SF12
SF12 changes are too small to see here either way. The outcome plots show a very small reduction in the intervention, which is what we would expect. However the magnitude is absolutely tiny.
![ED_SF_12](https://user-images.githubusercontent.com/44437206/222235572-30610015-0ae2-4b9d-9a39-c126c5b4273b.png)
### Housing Quality
Here is where things get interesting. The intervention shows an increase in housing_quality mean, which is what we would expect as lower values of housing quality are considered 'better' (better access to heating and household appliances). Therefore this plot is showing a reduction in housing quality in the intervention case.
![ED_housing](https://user-images.githubusercontent.com/44437206/222235603-9d5b87e9-3e7a-4850-b805-0142fed3449a.png)
### Neighbourhood Safety
Here we see a small reduction in neighbourhood safety mean in the intervention. Lower values are better here (1 == very safe neighourhood), so this is potentially the opposite of what we would expect, however the difference is very small and seems to move back to baseline by the end of the time period.
![ED_neighbourhood](https://user-images.githubusercontent.com/44437206/222235989-b0815cdb-68dc-4c1c-88c5-5027f1844a4d.png)
### Ncigs
Hard to say whether this is a real change or not, but there seems to be a very small increase in cigarette use in the intervention.
![ED_ncigs](https://user-images.githubusercontent.com/44437206/222235654-e868f903-edf9-48bc-adf4-e9dd94b94e82.png)
### Nutrition
WEIRD. Very consistent outputs here, with a lovely distinct difference between the two scenarios. Nutrition quality drops in the intervention, which is what we expect.
![ED_nutrition](https://user-images.githubusercontent.com/44437206/222235670-9fd1188b-f8d9-4184-bf88-501ec5c89c30.png)
### Loneliness
This is a sort of bonus plots, as loneliness is not used to predict SF-12 in this version of the code. I will test adding this back in and see what happens.
![ED_loneliness](https://user-images.githubusercontent.com/44437206/222235694-51a7ac7c-eb37-45f8-8607-e184675ac9d9.png)

The energy downlift intervention is by far the largest in terms of hh_income change, which also translates into the largest changes in the pathways. A little disappointing that this hasn't shown anything immediately that needs to be fixed. 

One thing that is very weird, is that nutrition quality seems to have the exact same response to all interventions. I.e. that noiseless plot with small reduction in the intervention case. 

Some ideas for what to look at next:
- Figure out why nutrition_quality has the exact same response to all interventions
- Make these same plots only including people who were boosted to make sure the boosts are driving these differences

**Comment by RobertClay** [comment]
linking #182  as they're related I think

**Comment by ld-archer** [comment]
Closing this as old and no longer necessary. `interventions.Rmd` does exist and still works but we don't have much use of it at the minute.
