### ISSUE TITLE
Automate N-dimensional loop for BaseHandler.transform_rate_table

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#217]
Moving from #211 as aide memoire, but not a priority and probably not necessary as there won't be any more variable to add after parity (see #167).

**Comment by RobertClay** [comment]
https://stackoverflow.com/questions/7186518/function-with-varying-number-of-for-loops-python

Recursion may be useful? Probably not worth the time to develop it unless you want to make a more generalised rate table constructor.

**Comment by paddy-r** [comment]
> https://stackoverflow.com/questions/7186518/function-with-varying-number-of-for-loops-python
> 
> Recursion may be useful? Probably not worth the time to develop it unless you want to make a more generalised rate table constructor.

Agreed, potentially a lot of work for the sake of neatness. And would probably not end up very neat as each loop level has variable-specific text/functionality.

**Comment by paddy-r** [comment]
Closing this as is unlikely to ever be necessary.
