### ISSUE TITLE
SF_12 PCS Pathways

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#239]
Need some additional modules and some modifications to others:

ok my takeaway for the income -> PCS pathways:
- housing (yes, as it is); 
- neighbourhood safety (yes, as it is); 
- Environment (green space, fast food etc. - will be difficult but may be proxies)
- diet and nutrition (yes, might be a bit more complicated but fine for now)
- access to private healthcare (??)
- Job related stressors (exposure to toxins, etc. - proxied by employment sector?)
- Tobacco (tes, as it is)
- access to gym membership, etc (??)
- Loneliness (as is)
- Chronic disease -> In my head 2 tiers but I think this is worth a discussion:
    - Some chronic diseases have relatively large impact on health (cancer, diabetes, CVD, many more)
    - Some less large impact (asthma, arthritis, hypertension(??), osteoporosis)
    - Do we make a distinction between the two? Or not include the less impactful ones? Seems like all chronic conditions would have a big enough effect on PCS that they should be included but also seems daft to have a separate module for each one
    - Multi-morbidities could be very important here. Maybe distinction between 1 or 1+ is important.

Steps:
- [x] Deep dive into the variable search to find variables we can use for these pathways (or ones we can use to create proxies)
    - Dump all information here so we keep a record of it 
- [x] Create modules for each of these using any current module skeleton as a starting point
    - [x] Alcohol
    - [x] Exercise/Fitness
    - [x] Material deprivation
    - [x] Chronic Disease
- [x] Create transition model equations for each module and add to the model_transitions.txt file
    - [x] Test that current code works to fit the models and iron out any data issues (i.e. missing years / small sample sizes)
- [x] Create transition model equation for PCS incorporating all these new modules
- [x] Add modules into the default_config.yaml file and do a test run
- [x] Visualise PCS outcomes separately from MCS when new modules are included
- [x] VALIDATION
    - PCS already included in handovers and soon to be in cross-validation
    - Handovers and cross-validation can both be run with single make commands (`make handovers`, `make cross_validation`)

NOTE: We don't need variables that span the entire length of data anymore, as we are currently only using the 2017-2018 model for SF_12_MCS. Therefore the only absolute thing we need is data for any variables that make up a pathway in 2017, as we need to be able to fit a one yearly model for the pathway variables (i.e. 2016-2017) and a one yearly model for SF_12_PCS (2017-2018).

[WORKING GOOGLE DOC](https://docs.google.com/document/d/1Scc2uYSwZJnNIEHcHs21JGuFaBOfhaD857w5E-GBNv0/edit?usp=sharing)

**Comment by ld-archer** [comment]
### Discussion Points

Early indications that there will be lots to discuss from this round of data discovery, so I'm listing them all here and will try to arrange a meeting most likely next week.

- Stress
    - This has to be a predictor of SF12 MCS, but could also be a predictor of PCS also
    - A quick search found multiple studies [1](https://journals.sagepub.com/doi/full/10.1177/0963721415581476?journalCode=cdpa#table1-0963721415581476) [2](https://jamanetwork.com/journals/jama/fullarticle/209083) [3](https://www.sciencedirect.com/science/article/abs/pii/S0306453020300184) that either link psychological stress to health outcomes, or explore the pathways that could lead from one to the other. 
    - However [others](https://www.sciencedirect.com/science/article/abs/pii/S0095454308000456) suggest that risk behaviours could be a big part of this puzzle, which we are already tracking (tobacco use, poorer nutrition etc.)

**Comment by ld-archer** [comment]
## Modules

After discussion on 8/6/23, these are the modules we have settled on as a good mix of important and achievable.

### Material Deprivation

[Data Discovery](https://docs.google.com/document/d/1Scc2uYSwZJnNIEHcHs21JGuFaBOfhaD857w5E-GBNv0/edit#heading=h.liwdr0gbdyc1)

Should be a simple proxy to create, we have a couple of 4 level ordinal variables asked to every household with either no pensioners or pensioners and children. Can just take the mean of these variables for a material deprivation composite. This should be related to hh_income (as questions are all '{do you have} enough money to i.e. keep your house in a decent state of repair?). 

### Exercise / Fitness
[Data Discovery](https://docs.google.com/document/d/1Scc2uYSwZJnNIEHcHs21JGuFaBOfhaD857w5E-GBNv0/edit#heading=h.k5aufv380gng)

Can use [government guidelines](https://www.gov.uk/government/collections/physical-activity-guidelines) to determine what is a healthy level of exercise vs unhealthy, then create a binary variable. Guidelines state that health activity level is at least 150 minutes of moderate intensity exercise, or 75 minutes vigorous intensity.

### Job Satisfaction
[Data Discovery](https://docs.google.com/document/d/1Scc2uYSwZJnNIEHcHs21JGuFaBOfhaD857w5E-GBNv0/edit#heading=h.g80vydqrfzty)

Can just use the [jbsat](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/jbsat) variable for this, although in the data discovery we have a large amount of related information that could be used to expand this in the areas of hours worked, working arrangements (part-time, on-call, work from home etc.), autonomy of work, psychological job stress (feels uneasy about job, feels depressed, miserable etc.).

### Alcohol Use

Have [AUDIT-PC](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1113176/Alcohol-use-disorders-identification-test-for-primary-care-AUDIT-PC_for-print.pdf) scores that we can use to create a 3 level ordinal:
- Low risk
- Increasing risk
- High risk

Which should make quite a simple module.

### Chronic Disease

Some work to do here before this can go into a module.
1. Fit a regression model for all chronic diseases to SF-12 (MCS & PCS)?
    - See if there is any obvious way of binning diseases, or if some can be safely ignored (i.e. small coefficient and insignificant)
2. Fit regression model for number of chronic diseases to SF-12.
    - i.e. 0 vs 1 vs 2 vs 3 vs 3+
    - Is a number of chronic diseases more useful than tiers? Is it easier to predict?

**Comment by paddy-r** [comment]
May be way to complicated an approach, but for quantitative measure of severity of chronic disease, how about years of life lost (YLL)? Quick search found this for Germany, see Figure 2, it's also age-specific. So for a given age group, (relative) severity of disease is proportion of YLL.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8212398/

**Comment by ld-archer** [comment]
Looks like a good place to start and could be used to justify any decisions we make, cheers!

**Comment by paddy-r** [comment]
> Looks like a good place to start and could be used to justify any decisions we make, cheers!

Looks like data for England and Wales are available in massive detail...

https://digital.nhs.uk/data-and-information/publications/statistical/compendium-mortality/current/years-of-life-lost

Of the US variables you found, it looks like most are present one-to-one, e.g. asthma, coronary heart disease, others present but not one-to-one, e.g. emphysema comes under "bronchitis and emphysema".

**Comment by ld-archer** [comment]
# Alcohol

_Docstring from generate_composite_vars.calculate_auditc_score():_

Alcohol use disorders can be assessed via the AUDITC score. This score is derived from 3 questions that form part of
the full 10 question AUDIT screening test, where AUDITC specifically focuses on consumption. The 3 questions are:

1. How often do you have a drink containing alcohol?
2. How many units of alcohol do you drink on a typical day when you are drinking?
3. How often have you had 6 or more units if female, or 8 or more if male, on a single occasion in the last year?

Each question is ordinal with 5 levels, depending on the 'severity' of the answer. We then score each question from
0-4, with higher scores meaning higher 'severity'. The total across the 3 questions then creates a score from 0-12,
with 0-4 meaning sensible drinking, 5-7 meaning hazardous drinking, and 8+ meaning harmful drinking.
See following link for information on scoring:
https://www.drinktalkingportal.co.uk/clinical-guidance/alcohol-abuse-screening/alcohol-audit-audit-c

To calculate this score, ee rely on 4 variables in Understanding Society shown at the following link:
https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation?search_api_views_fulltext=auditc

Question 1 above relies on auditc1 & auditc3, question 2 relies on auditc4, and question 3 uses auditc5.

NOTE: The final variable used (auditc5) specifically mentions 6 or more drink frequency, rather than 6+/8+ units.
        This could be a mistake in the description or the actual question asked being incorrect (not the true AUDITC
        question). There's no information about which one it is, so I'm treating it the same as the AUDITC3 question
        for our purposes. Added benefit that this is simpler to code without checking for gender also.

### Sample Check

![image](https://github.com/Leeds-MRG/Minos/assets/44437206/478a0130-b770-416a-8c16-6472291215d1)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/3deca380-0349-4f25-939c-133af5df417a)

Interesting here that the number of missing values jumps in 2020. Assuming this has something to do with COVID? Maybe people were less happy to talk about their consumption during COVID lockdowns? Unfortunately due to the lack of information on the website we don't have any idea why... There is some literature using these variables though so I'll have a look through that also. 

### Handovers

![image](https://github.com/Leeds-MRG/Minos/assets/44437206/7b8a7e10-f9b6-4526-bfe7-bf5e18e88ef3)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/48547889-547b-4ca7-a8c3-85eb6dee3076)


### Cross-Validation

Incoming, some weird error happening with Cross-val that isn't happening with normal simulation. Nothing is ever simple...

**Comment by ld-archer** [comment]
## Current PCS Plots

This is with the following variables as predictors of PCS:
- PCS 
- age 
- sex 
- ethnicity 
- housing_quality 
- tobacco 
- nutrition_quality 
- loneliness 
- financial_situation 
- alcohol

Arguments to be made I think over loneliness and financial situation, will take some time before merging any of this work to get literature backing for any decisions we make.

### Handovers
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/81b34a70-c642-48e3-9587-8136e7ebfba6)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/3e01ecd7-215d-42f7-a7ad-1b6d3f6bd3ea)

### Cross-Validation
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/3491956f-3db4-41ca-a472-d8b0f12ef26d)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/5333bf7a-d7b8-4f4b-ba79-1e5a2efa0518)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/64414e06-e36e-4ed1-b025-7452155f1086)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/b252f575-94f9-43bb-8a82-c29dc4718d63)
![image](https://github.com/Leeds-MRG/Minos/assets/44437206/34ccf343-d485-4251-b300-93596a977582)

**Comment by ld-archer** [comment]
Happy with pathways at the mo (few issues to resolve still but we have a working model) so closing this now.
