### ISSUE TITLE
Data discovery of housing variables

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#251]
Need a table of variables on the housing front that we can pass to SIPHER colleagues and continue the discussion around what we can achieve.

Either posting the table here or as a google document would be quite good so we all have access to a living copy.

Domains:
- Housing cost
- Tenure type
- Housing quality
    - Heating
    - S7 housing quality
    - More??
- Neighbourhood Safety
- Neighbourhood amenities
    - Green space
    - Youth facilities?
    - Goods and services (i.e. gym / fast food / supermarkets)?
- Transport (public transport only?)
- Overcrowding
- Community??
    - Not sure about this one but examples could be:
        - ethnic diversity / migrant communities
        - language barriers?
- Fuel consumption (CO2 emissions?)

If any points are wrong or missing please correct.

[WORKING DOC (Google doc)](https://docs.google.com/document/d/1yE0TbgTzzUU7BXdBVMvoqGzt6HvtMNYIHGDskHztDvk/edit?usp=sharing)

**Comment by ld-archer** [comment]
Added fuel consumption cheers. 

Maybe housing debt as part of housing costs? I think financial perception is too far from housing quality to be included here. Maybe as a pathway variable.

On a slight tangent, if you've found good variables for financial perception then should we add these to the hh_income model? That was a suggested pathway but I thought we had discounted it due to no good data.

**Comment by RobertClay** [comment]
may be a good time to move towards estimating gross income and overheads in an income module too? There are some good data e.g. https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/finnow

**Comment by ld-archer** [comment]
Closing this as completed a while ago (see trello information list for Housing Data Discovery card).
