### ISSUE TITLE
Investigate alternatives to "nkids" variable

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#256]
Prompted by discussion on 01/06/23 and during fertility development (i.e. #167, #211, #226), need to investigate alternative to ```nkids``` variable in Minos, as this is the number of children in an individual's household, not how many children they have personally.

**Comment by ld-archer** [comment]
Found this: [Number of dependent children in household](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/ndepchl_dv). Still not complete picture but better than nkids.

**Comment by paddy-r** [comment]
> Found this: [Number of dependent children in household](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/ndepchl_dv). Still not complete picture but better than nkids.

Definitely better! Also found nchild_dv, so here's what we have so far.

- [ndepchl_dv](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/ndepchl_dv), definition: "Number of own dependent children in the household. This uses the Department for Work and Pension (DWP)'s definition of a dependent child."

- [nchild_dv](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/nchild_dv) (number of own children in household), definition: "Number of own children in the household. Includes natural children, adopted children and step children, under age of 16."

**Comment by paddy-r** [comment]
Also found this variable, which might be what we want, although couldn't find it in Minos output files:

- [lnprnt](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/lnprnt), definition: "number of biological children ever had/fathered"

The nuclear-option alternative to *estimate* the number of children someone has is to use the logic already developed for #167/#209 (not pushed yet), i.e. given the age of the woman, how many children does she have? That is, calculate $P(n_k | a)$, then sample. Very simple, uses ```numpy.random.choice```, using [ONS 1934-2020 fertility dataset](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/conceptionandfertilityrates/adhocs/14363fertilityratesbyparity1934to2020englandandwales), although not disaggregated by ethnicity.

Middle way/if ```lnprnt``` isn't suitable or available in all cases, there are also these variables, which it might be possible to combine into a good estimate, although we'd have to think about the logic. The issue seems to be that US variables on number of children are only concerned with those *living in the household*, so doesn't include any others, i.e. any children <15/16y living elsewhere (at least I can't find any current US variables on that at all) or children >16yo.

- [ch1by4](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/ch1by4), definition: "year first child born"
- [nchild](https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/nchild), definition: "How many children have you had since ff_IntDate?"

Rough logic could be some combination of:
1. If $a$ > 30 (i.e. age above which there is a significant chance one or more of her children are older than 15/16), estimate number of older children (see above)
2. Over life of individual, sum values of ```nchild```
3. If ```ch1by4``` value exists but ```nchild_dv``` and/or ```ndepchl_dv``` is/are non-zero, estimate number of children, as suggests individual may have older children
4. ???
5. $$$

**Comment by RobertClay** [comment]
Seems like we're going to need variables for number of children total and number of dependent children in the household. 

lnprnt looks good to me but needs some imputation. There are a lot of missing values due to people with no children and no forward filling. Imputation strategy might look like this

- deterministic imputation to calculate any parents who have never had children (assign them 0). 
- after that forward fill using locf. 
- in MINOS fertility rate tables that give a positive just incremement this value by 1.
- some other kind of handling for when they reach working age (simpler) or move out (very complicated).

**Comment by paddy-r** [comment]
Following discussion, have replaced ```nkids_dv: nkids``` (US name: Minos name) with combination of two variables: ```lnprnt: nkids_ind_raw``` (number of children ever had; only asked at initial interview, so needs to be updated) + cumulative sum of ```preg: nkids_ind_new``` (whether pregnant at interview) = ```nkids_ind``` (total number of children ever had).

**Comment by paddy-r** [comment]
Closed with #259.
