### ISSUE TITLE
Fix or replace complete case

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#277]
Complete case of one or more variables is resulting in spikes and troughs in sample sizes, which causes problems for our validation due to the counts and proportions being off. We currently run a lot of variables through complete case, some for the whole period of data, and some for specific years (as they aren't available for the whole period). We probably need some investigation initially to figure out if it is just one or a small group of variables that are causing the big sample size reductions. See the drop in mean hh_income in 2013 here as an example of the problem:
![hh_income_wav1](https://github.com/Leeds-MRG/Minos/assets/44437206/08231835-11af-4cb3-99e3-2e661dab444b)
And see the sample drop in the same year that causes it (via counts by education state):
![cv_education_state_count](https://github.com/Leeds-MRG/Minos/assets/44437206/f9039524-528a-4804-9268-e1c285144fe6)

We might want to replace complete case for certain variables with a form of imputation such as mean substitution or hotdecking, or if possible find a way of imputing based on additional variables or information. As said above, the first step is to identify which variable has low sample size in 2013 which is actually causing this problem.

**Comment by ld-archer** [comment]
Note: I think the culprit is one of the variables that run through complete_case_custom_years(), so not in the large list of complete case variables. When I switched off all the custom years variables the problem was gone, so we can probably narrow the main culprit down to one or more of ncigs, S7_physical_health, S7_mental_health, or S7_labour_state, as these are the ones that run through complete case for 2013. Still, if we find a better solution than complete case then its worth replacing the rest of the sample with it. 

Maybe we can stop doing complete case altogether and just handle missing data during transition model estimation? We would have larger samples for each transition model then, and we could be less stringent on the samples for the input populations with hotdecking or mean substitution without worrying about biasing the models. Larger stock and replenishing populations would be a nice side effect.

**Comment by RobertClay** [comment]
you may like the VIM package for this https://boostedml.com/2020/05/visualizing-missing-data-in-r-the-basics-with-vim.html

**Comment by ld-archer** [comment]
Closing this as old and the problem being fixed (ncigs heavily missing in 1 wave causing sample issues). Complete case will also be replaced gradually by MICE imputation.
