### ISSUE TITLE
Tidying up component priorities throughout pipeline

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#291]
During #259, disparity between priority of components came up and need to be fixed. Stages in pipeline are:

1. User specifies components to be included in simulation in config file.
2. The order of components is then determined automatically via a dictionary in ```RunPipeline```, as of [019cb4c](https://github.com/Leeds-MRG/Minos/pull/259/commits/019cb4c99756bc491ad8040b2782d9c27c8f4c90), [be59252](https://github.com/Leeds-MRG/Minos/pull/259/commits/be59252fd0b968d39d8b0284826a3f1bb4da8529), etc., in #259.
3. Components are then also assigned priorities during initialisation within their ```setup``` method in the ```builder.event.register_listener``` line, but these priorities don't always match those in ```RunPipeline```.

Want to make sure:

* [x] Priorities in ```RunPipeline``` and setup methods match.
* [x] Mortality higher priority than fertility to avoid killing new mothers.
* [x] Order should be:

0. Replenishment
1. Mortality
2. Fertility
3. Education
4. Intervention (all classes in ```intervention.py```)
5. Income (all classes in ```income.py```)
6. All other pathways (e.g. housing, neighbourhood, tobacco)
7. ...except mental wellbeing (all classes in ```mental_wellbeing.py```), which comes last here

* [x] For SIPHER7 variables (anything beginning with ```S7_```) apply priority = 6 except equivalent income which is 7.
* [x] Income modules need to be corrected as properly specified in ```RunPipeline``` priority dict (e.g. was ```geeIncome```, should be ```geeIncome()```).

N.B. Not changing ```base_population``` priority as doesn't seem to be used. Noting here for posterity.

**Comment by ld-archer** [comment]
Can we close this @paddy-r ?

**Comment by paddy-r** [comment]
> Can we close this @paddy-r ?

Not yet, needs some attention still.

**Comment by paddy-r** [comment]
Component priorities handled manually in #283/#285 (via ```RunPipeline.validate_components```) rather than being automated (via ```RunPipeline.validate_and_sort_components```, as elsewhere). Needs to be done consistently everywhere, but leave until after SG meeting at end of Jan. '24. Therefore have converted #292 to draft for now.

**Comment by paddy-r** [comment]
Closed with #292.
