### ISSUE TITLE
Get pipeline running

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#3]
I've f###ed up here and omitted good chunks of what's needed to run pipeline. Need to get it working. Make sure right rate tables etc are being used and not from daedalus that include location variables.

**Comment by ld-archer** [comment]
Consider issue #7 when working on the pipeline. One of the tasks for this issue is to re-factor the rate tables used in the pipeline up to regional level (from LAD).

**Comment by ld-archer** [comment]
Closed in PR #13
