### ISSUE TITLE
updating new living wage values. 

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#317]
As per Petra, the living wage figures have been updated again in Scotland to over £13. 

Worth impementing this in terms of change over time.

Easy intervention to write up and rerun plots for.

**Comment by ld-archer** [comment]
[Living Wage Foundation](https://www.livingwage.org.uk/) has also increased their values by a sizeable chunk. This will probably need to coincide with rebasing the current £ value to a 2023 based value as the difference there could be important ([CPI for 2023](https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest), [data here in table 7](https://www.ons.gov.uk/file?uri=/economy/inflationandpriceindices/datasets/consumerpriceinflation/current/consumerpriceinflationdetailedreferencetables.xlsx)). 

I'll take this one as I'm going to look into the cost-effectiveness of these with QALYs, and could combine this with another recent [piece of news from UK Gov (see 2 Oct)](https://www.theguardian.com/politics/live/2023/oct/02/conservative-party-conference-jeremy-hunt-liz-truss-rishi-sunak-tory-labour-politics-latest-updates?filterKeyEvents=false&page=with:block-651a62298f087e532d8e0634#block-651a62298f087e532d8e0634) where they want to raise the minimum wage to ~£11 ([which they also call the living wage annoyingly...](https://www.theguardian.com/society/reality-check/2015/jul/08/george-osborne-budget-national-living-wage)).

**Comment by RobertClay** [comment]
I think we're going with the living wage foundation's suggested version rather than the actual government one.

**Comment by ld-archer** [comment]
Yeah what the government call the living wage is actually just their new name for the minimum wage, so could be good to model the increase in the new minimum wage as well as the potential living wage. 

I don't think we need to vary the values we use as long as we rebase the £ value to the most recent point. Seems reasonable to keep doing what we are doing but just updating the inflation adjustment and living wage values.

**Comment by ld-archer** [comment]
Should have been closed with PR. Will open a new issue for minimum wage intervention increase.
