### ISSUE TITLE
Unblackboxing of how the US_super_output.geojson is made

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#322]
In my infinite wisdom I've not really explained anywhere how we generate this and we'll definitely be asked this in the future so I'm putting an issue for integration of how UK_super_outputs.geojson is generated into a README somewhere.

- [ ] readme for merge_geojsons.py
- [ ] where we get UK/scot maps from. (can we get these from URLs in python? more robust directory?)
- [ ] preprocessing in mapshaper.org to convert scot data to WGS84 coords (lat/long) (can this be pure python?)
- [ ] merging of two geojsons together 
- [ ] removing any overlaps at the scottish borders? (again, python?)

**Comment by RobertClay** [comment]
@paddy-r do you mind if I hand this off to you? Can discuss in detail but need to automate this ideally and put it in README/docs.

**Comment by paddy-r** [comment]
Closed with #389.
