### ISSUE TITLE
Find the best way to install R packages either in Dockerfile or Makefile

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#33]
Need R packages to be installed as requirements, but would be good to find a way to do this that maintains the agnosticism of the Makefile (i.e. the current Makefile can be run by any user or within docker and do what it needs to do without any user input or changing paths etc.). 

Handling in the Dockerfile comes with its own shortcomings (increasing size of the image, only handled in the image) but would be possible.

**Comment by RobertClay** [comment]
env files may be useful too. https://stackoverflow.com/questions/12291418/how-can-i-make-r-read-my-environmental-variables

**Comment by ld-archer** [comment]
Problem now solved in [this commit](https://github.com/Leeds-MRG/Minos/commit/ce139d8e211523fa48a600d66137c43e61900c54).

Rob wrote an 'install.R' script thats kept at the top level of the project directory, which is run via the Makefile as part of the install target. This works on any machine as well as docker image, and can be added to when necessary.
