### ISSUE TITLE
How to best import R models into python

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#34]
improve on current method  of using R methods in python. 

currently loads csvs to R, processes new values, and sends csvs back to python.

luke suggests loading in coefficient vectors/other essentials instead. 

implies saving weight vectors from R to csvs, load coefficients into python, and calculate desired linear sums directly in python.

- [ ] produce regression in R and save coefficient vector as csv (hdf5 better? some way to import R object .rta files as dicts?)
- [ ] import coef vector into python. 
- [ ] Format python data to match coefficient vector (just encoding oneshotted factors properly? may be more generally worth oneshotting entire vivarium frame rather than reencoding back and forth.) 
- [ ] final variable estimation. predict() functions in R can be fairly complicated especially for predicting direct class types rather than linear predictors.

**Comment by ld-archer** [comment]
### Example Income Transition Model

[income.csv](https://github.com/Leeds-MRG/Minos/files/8370691/income.csv)

Variables | model.coefficients
-- | --
(Intercept) | 921.011466951154
age | 7.25998280332895
sexMale | 100.881387369326
education_state-9 | 310.264081970755
education_state-8 | 336.490825052906
education_stateCSE | 163.292489798494
education_stateGCSE | 240.242617309523
education_stateA-Level | 471.821175633234
education_stateHE Diploma | 521.633387904113
education_stateDegree | 825.975257024994
education_stateHigher Degree | 969.324454988834
ethnicityWHO | -95.1777350330042
ethnicityMIX | -154.195634982476
ethnicityIND | -224.91012466727
ethnicityPAK | -588.587904220579
ethnicityBAN | -541.011227747233
ethnicityCHI | -98.975296087308
ethnicityOAS | -170.046877693235
ethnicityBLC | -427.924907220303
ethnicityBLA | -623.202651879108
ethnicityOBL | -387.681180550437
ethnicityOTH | -342.417719345234

**Comment by RobertClay** [comment]
looks good to me. It should integrate pretty well with vivarium so long as we output a prob distribution matrix for builder.random to draw from. I appreciate OLS gives a direct vector of predictions but it still works and generalises nicely.

**Comment by ld-archer** [comment]
Just found this note in the Vivarium docs about priority:

> Listeners are stored in priority levels when registered to an event. These levels (0-9) indicate which order listeners should be called when the event is emitted; listeners in lower priority levels will be called earlier. Within a priority level, there is no guarantee of order.

> This feature should be avoided if possible. Components should strive to obey the Markov property as they transform the state table: the state of the simulation at the beginning of the next time step should only depend on the current state of the system.

It seems that modules that share a priority level are still done 1 by 1, we just can't be sure of the order. Because of this I'm going to look into another way of maintaining the Markov property and open a new issue for it.

**Comment by RobertClay** [comment]
seems done for now. RSE team may find a better way if we go through with it
