### ISSUE TITLE
unblackboxing of X_data_zones.csv files. 

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#384]
creating script to generate these X_data_zones.csv files used in mapping from single file. 

- get UK lookup file.
- split file according to required subgroups (scotland,glasgow,sheffield,manchester)
- take single desired column of lsoa11cd. 
- save to files with required names in persistent_data/spatial_data

**Comment by paddy-r** [comment]
@RobertClay Beat me to it!

**Comment by paddy-r** [comment]
Closed with #385 but also see #389.
