### ISSUE TITLE
Scottish Child Payments interventions - Separate Branch

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#402]
Need to collect the changes for Scottish Child Payments onto a separate branch so they can be merged into development and other places. These changes exist already in a few branches but they are mixed with some other large changes and hard to isolate.

Files with important changes:
- [x] ChildUplift intervention class
- [x] aggregate_subset_functions new subset for UC households
- [x] data gen adding universal credit
- [x] RunPipeline intervention kwards

Important changes in outcomes files:
- [x] make_lineplots
- [x] make_lineplots_macros
- [x] outcome/Makefile

**Comment by paddy-r** [comment]
Anything from my end already in #366/#374 and PR #393. Some more jobs in #396 but nothing urgent.

**Comment by ld-archer** [comment]
Finished and merged with PR #404
