### ISSUE TITLE
Retaining all US individuals through data generation pipeline

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#444]
Issue arose during fertility model development/write-up, May '24 onwards. Would like to retain all individuals in US data, and not remove any, as is currently the case. E.g. for 2020 data, i.e. synthpop year ("2019" in Minos nomenclature), 58.0% of pidps in US raw data are retained at the `final_US` stage.  Overview: set of ids present in raw US data is $S1$, set in `final_US` (i.e. Minos presim population) is $S2$. If ids are removed then $|S1 - S2| > 0$.

Motivation within fertility model development is to ensure input population is representative - of GB, when synthpop is used and of UK when US population is used (when weights applied).

Following discussion with Rob, two options:
- Continue to develop pared down MS outside Minos with bare essentials (fertility, mortality, ageing, replenishment). Much faster (c. 20ms per individual with Minos presim population, 500ms in Minos; 10ms with 10% synthpop, so probably $O(log(n))$ or so due to vectorisation) but not rigorous, particular for replenishing population, and requires a lot of functionality to be copied and pasted from Minos (e.g. composite variable generation).
- Better option is to group any functionality in Minos data generation pipeline where individuals are removed, and move them to single point in pipeline, which can be turned on/off as option in config.

Points in pipeline where ids removed (may be more):

- [x] Pre-raw. `US_format_raw`: `data = data.loc[~data["pidp"].isnull()]` in `main`. -> Removal has no effect, marking as done.
- [x] Pre-raw. `US_format_raw`: in `combine_indresp_hhresp`, some ids in hh data not present in ind data; changed from (default) inner join (i.e. intersection of hh and ind keys, `how='inner'`) ~~to outer (union of hh and ind keys, `how='outer'`). N.b. left outer join (`how='left'`, ind keys only) has same effect. -> https://github.com/Leeds-MRG/Minos/pull/439/commits/8365339068ce20e26c803a93f989da55d7816c7f~~ -> nope, actual fix (to left outer join, `how='left'`) in https://github.com/Leeds-MRG/Minos/pull/439/commits/3e5f1db53ba9ba67d15d4d48cb143b7a2f17c148
- [x] Raw -> corrected. `US_missing_main`: sparse individuals removed in `restrict_chains`. -> This and following two instances done in https://github.com/Leeds-MRG/Minos/pull/439/commits/7f2b67d14d5b80d722561dc99717c3619aaadc9a; preserves all pidps in raw -> corrected stage.
- [x] Raw -> corrected. `US_missing_data_correction`: sparse individuals removed in `restrict_chains`.
- [x] Raw -> corrected. `US_missing_data_correction`: outliers removed in `restrict_variables`.
- [x] Corrected -> composite. None found. No removals present in GCV, but did some Pandas future-proofing -> https://github.com/Leeds-MRG/Minos/pull/439/commits/cb7c00734c56022df996de91c3d53f8a7e9ff893
- [x] Composite -> complete. `US_complete_case`: `data = data.loc[~(data['child_ages'].str.contains('-9') == True)]` in main block. -> this and following four items done in https://github.com/Leeds-MRG/Minos/pull/439/commits/7ea0bae6faef677e3846df87a8b17f6bc498024d
- [x] Composite -> complete. `US_complete_case`: empty ids removed (?) in `complete_case'.
- [x] Composite -> complete. `US_complete_case`: empty ids removed (?) in `complete_case_varlist'.
- [x] Composite -> complete. `US_complete_case`: empty ids removed (?) in `complete_case_custom_years'.
- [x] Composite -> complete. `US_complete_case`: outliers removed in `cut_outliers`.
- [x] Complete -> final. Could not find instances of removals, but could be in `generate_stock_pop`? -> done in https://github.com/Leeds-MRG/Minos/pull/439/commits/480645f320d7f6e92dd21618b8e5b0262b24c69d, changed inner join to left outer join in merge (`how='left'`) as elsewhere in `generate_stock_pop`.

Already have code for testing for id retention, numbers shown below for 2020 (Minos 2019) data.

![image](https://github.com/Leeds-MRG/Minos/assets/50209911/14e6bc7c-08ec-4ba3-b7d2-b01cde716adc)

...so another job is to verify this.

- [x] Verify 100% id retention. -> done (confirmed okay after https://github.com/Leeds-MRG/Minos/pull/439/commits/71f26d9ae126803007bbdc30c08426c8e916cb26), see figure below

![image](https://github.com/Leeds-MRG/Minos/assets/50209911/4f3dfab9-7ffb-411b-817d-ad161be1d328)

Another issue (see discrepancy of 2 between US and Minos raw numbers in figure above) exists that I'll look at: new ids are created during data generation, i.e. $|S2 - S1| > 0$ at some stages of DG pipeline (some years only). Vanishingly small number so can maybe be removed for the purpose of this fertility job, but worth looking at.

- [x] Quantify new ids during data generation. Marking as done, as I was using different version of US data (different wave, presumably previous years of data are slightly different as a result of updates).

Will roll all this into fertility development/testing as all linked. Couple of other things to try, which all go towards running Minos in "lite" mode that might be useful in future, e.g. for Jo&atilde;o et al.:

- [x] ~~Parse only necessary variables (age, sex, region, ethnicity, nkids, nkids_ind) in `US_format_raw`. May not be possible, as huge number of dependent/composite variables are produced in data generation...~~ -> marking as done as not a good idea; current plan is to be as light-touch as possible for possible merging back into `development` later'.
- [x] Pare down config file to essentials (fertility, mortality, ageing, replenishment). -> done in https://github.com/Leeds-MRG/Minos/pull/439/commits/a2450117af067a1ae40071c4a5c84c868731fa1f by way of new config files and make commands

**Comment by RobertClay** [comment]
all can be immediately just hashed out 
 Raw -> corrected. US_missing_main: sparse individuals removed in restrict_chains.
Raw -> corrected. US_missing_data_correction: sparse individuals removed in restrict_chains.
Raw -> corrected. US_missing_data_correction: outliers removed in restrict_variables.

might get some key errors for northern ireland in council tax calculation though.

**Comment by RobertClay** [comment]
Now I think about it its another odd job to get NI rates working in the same way as the rest of GB. 
We can pull rates by county into a csv (theres not many councils in NI. like 14?)
Rates are calculated on property values. can find this for homeowners fairly easily in US I think?
as always an annoying gap for renters.
https://www.nidirect.gov.uk/sites/default/files/publications/how-my-rate-bill-is-calculated-fact-sheet-august-2019_0.pdf

wondering how good a map from rent cost to property value is. probably mediocre at best.

**Comment by paddy-r** [comment]
> Now I think about it its another odd job to get NI rates working in the same way as the rest of GB. We can pull rates by county into a csv (theres not many councils in NI. like 14?) Rates are calculated on property values. can find this for homeowners fairly easily in US I think? as always an annoying gap for renters. https://www.nidirect.gov.uk/sites/default/files/publications/how-my-rate-bill-is-calculated-fact-sheet-august-2019_0.pdf
> 
> wondering how good a map from rent cost to property value is. probably mediocre at best.

Currently nanning NI council tax in https://github.com/Leeds-MRG/Minos/pull/439/commits/11abf9c95212bcf92ac2cfa08c4269cbd584e539 for sake of getting some fertility results out, but let's raise a new issue if it comes to it.

**Comment by paddy-r** [comment]
Going to close this as done, as all points in original comment at the top are done incidentally within PR #439. Will then update #369 and split off into new issues, if it's more intelligible to.
