### ISSUE TITLE
Implement living wage intervention strategy

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#60]
Intervention to increase the household disposable income (`hh_income`) for all people who are not currently earning a living wage.

This needs to be based on individual income variable (see early versions of MINOS for logic on how to calculate for different sub-groups). We need to select all people who earn under a specific value (£9.90 nationally, £11.05 in London), and increase their `hh_income` by a specific amount/percentage. 

Challenges from previous implementations are based around people who are self-employed or employed part time. Some employment groups (by NSSEC code) were more or less likely to be below living wage, and some of these were most likely propped up by other sources of income such as small business owners using business income for personal expenses.

**Comment by RobertClay** [comment]
tbd for sipher meeting. how do we quantify this. move people below the poverty line upwards. Refer to Ping's talk is best imo. Grab slides from sipher drive.
