### ISSUE TITLE
Fix neighborhood safety composite

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#71]
Everybody has the same value for neighborhood safety (1). This needs fixing, and when it has been fixed it can be added back to the SF-12 OLS model (currently removed to stop errors).

**Comment by RobertClay** [comment]
Need to do some analysis and maybe discuss with Aki at some point. Main issue is refactoring of comoposite to have more even classes. Worth some exploration in R. e.g. which of the neighbourhood issues is most indicative of uninclusive economy.

**Comment by ld-archer** [comment]
This was completed in branch 84, and brought into the development branch when it was created from branch 113. Neighbourhood Safety composite is now much more evenly binned than previously, and seems to be working fairly well.
