### ISSUE TITLE
yaml overwriting on hpc leading to failed runs

### ISSUE THREAD

**Issue by RobertClay** [Leeds-MRG/Minos#89]
batch runs on hpc sometimes fail due to yaml config not being found.

think this is due to many runs trying to access the yaml file at once and failing to do so. 

need some way around this.

stop any writing of the config in the batch run main. removae all file path names to the config. 

stop plotting in batch run. save until after using make command with IDs.

**Comment by ld-archer** [comment]
This issue should have been solved through run script refactor so I'm going to tie it to that PR. Last thing to do is remove the unimportant pieces from the configs so I'll  do that now.
