### ISSUE TITLE
Refactor run scripts so we have a single point of entry

### ISSUE THREAD

**Issue by ld-archer** [Leeds-MRG/Minos#90]
Currently we use separate scripts for different run types:
- run.py : testRun and similar local single runs
- minos_batch_run.py : Multiple runs on arc/beefy
- minos_parallel_run.py : WIP multithreading, not sure it can work
- run_in_console.py : Pretty much just a version of run.py that has parameters hardcoded for debugging and stuff

This is not the most efficient way to do things, as it means some changes have to be copied between run.py and minos_batch_run.py to run the same model. We want to have a single point of entry (a `run` script) that can be called from different wrapper scripts or makefile targets to do different jobs, but always ensures we are running exactly the same version of the model when doing so. For example, the `testRun` target is for a quick local run that can be used for debugging, so should just run the `run.py` script once, whereas batch runs on HPC or beefy will need to run many times, so need to call the `run.py` script multiple times. In each case, the model should run exactly the same with the same parameters (so config doesn't need to change), just the output directory(s) (with an additional `run_id` argument supplied in batch runs).

In practice this means updating the `run.py` script with some new features of the `minos_batch_run.py` script, removing the output directory from the config file so it can be passed as an argument to `run.py`, and creating a bash script to act as a wrapper around `run.py` when running batches of simulations. 

Not sure this issue description is very clear, but it is very clear in my head.

**Comment by RobertClay** [comment]
see #89 for other config/run.py refactor requirements.

**Comment by ld-archer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor the run script so we have a single point of entry](https://trello.com/c/3zET3OFG/130-refactor-the-run-script-so-we-have-a-single-point-of-entry)
